sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    # travis encrypt -r smoketurner/graphiak CI_DEPLOY_USERNAME=
    - secure: "0Z5H47SjEIwqcqv7owqlgWHot90Y5mjzPgzZb4iltMvCmgHuEaSOWbHwU808JyefoFMgzP8Nd1bDh2lNVbFsiUQLbdpY/owj07SccUn84XKxlCNuoocXc2zw7ltmANW4uUh4Je1VyOVlkffQedaPtOtqOnv1Q1E9Au08dsmlF52bAdOMXGWixOZiI+V6HjARW3EtXxbkTkf3Gj23VY71w1fel/n+uk97PDrgUxxCOx60rJkMUQbQn4zT9h6bIqG7XmlcEFFo+lPyhY9ZZ10EVD4gegkyCnkE9X1bjjtHwIAyc5GLiqiuU0FM5DsHLjfg6i/0F14lUl9orlDf7jxpdJ3gof2p6ePwrm7lEyGMZKRclfa0DuWReaH+CzLHqE6WRvAUUiuYBTwFqyERGeN7VEfst7OEGfJmT3gh+MA+dqHLzgzkC23i2+JRGXFEM4JkEoRNaaiieM6w0MBv+zwLy8KjGiBM3hHdZdIjykO58TxM91HF3GHGeM27kwEg2B2pztPhju+AcxDRzhNJIotzkzkDwYfQ60Uhj9p9RVhJSoeZg1REEOc3yXK92uKiHL3q6Vh6MZ59ZMuCjiy1633Ygm5L5ytuhe++RQVyGxI9NlVSAavmFM47zRL4jUhpHzBwxj3fhdkb8ZdULNm244JNIruOo3gTAUvncqgl5YSm5L8="
    # travis encrypt -r smoketurner/graphiak CI_DEPLOY_PASSWORD=
    - secure: "D8dyO+nzUk40Ajbfw3Fr2Ml/KcWGVXR7WFREXdw93Q8ND/zxwN4Z6HIzGP5Q/BcSUW/Fv65AmRXYbZww0nqrv0EHE3KrexmwFs97u5dR+9G8zRMBfCIo8qjLmp6BMf4zCrZfKTiggCWMUq+5/AN3kUjspkZk1UrCfWgHhE2yWZEXRPmATa+M8Peco1xKlW/uLhZIy1UXFxiikYLciiYTzuABO+PA72Qx9Q1JgDERKzzccWGvO4KFAWyodM1mKTtiCKtbIFHhtTVkdTsF5bylspV2cwj13G48Vw0UV7w8LkfWzVqD3oxKjxZR0MT9nCI0423JeGb+ozPRNj2cJOScp6MQ5aPJoLRsVCPs34/uElmtC3ePA/GBElkUAm5hwmSEItbUASRXzCgvJqW12LrUXTtgxP3cJFB7nAISox8gEco4ivD27gEtycYBCkDFtxYRP26viNgbWUmQBwKYDqBjY6dzMCO4fDBPf+wT1TpFBR519gdLfnHUK8fn8AskXwHLRYSaUMqvjF99KO3+FgrHEuL8pfi/okPUzju2Q7NXbnG5HLHExYo7z2zHeb30M4x7R6wma5PbCtQuf2yVNe3ZRj01hLpVQLVnAPbLKJCn1Iif4KwXEyV6t/r9DyXCg/8YfKVBnW5DvuiZHG/DWqGYfbRBRKCS+c0nFMolupb0rcg="
