# Netty-specific options.
netty:

  # Port to listen on for new metrics
  listenPort: ${PORT:-2003}

# Riak-specific options.
riak:

  nodes:
    - 127.0.0.1:8087

# HTTP-specific options.
server:
  type: simple
  minThreads: 1
  maxThreads: 3
  applicationContextPath: /
  connector:
    type: http
    port: 8080
    acceptorThreads: 1
    selectorThreads: 1

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.graphiak: INFO
    com.basho.riak: INFO
    io.netty: INFO
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
